// SPDX-License-Identifier: Apache-2.0

const ethers = require('ethers');

const Events = {
  Success: 'success',
  ResponseCode: 'ResponseCode',
  AllowanceValue: 'AllowanceValue',
  ApprovedAddress: 'ApprovedAddress',
  Approved: 'Approved',
  Frozen: 'Frozen',
  KycGranted: 'KycGranted',
  TokenCustomFees: 'TokenCustomFees',
  TokenDefaultFreezeStatus: 'TokenDefaultFreezeStatus',
  TokenDefaultKycStatus: 'TokenDefaultKycStatus',
  TokenExpiryInfo: 'TokenExpiryInfo',
  FungibleTokenInfo: 'FungibleTokenInfo',
  TokenInfo: 'TokenInfo',
  TokenKey: 'TokenKey',
  NonFungibleTokenInfo: 'NonFungibleTokenInfo',
  IsToken: 'IsToken',
  TokenType: 'TokenType',
  Approval: 'Approval',
  ApprovalForAll: 'ApprovalForAll',
  TokenCreated: 'TokenCreated',
  TokenCreatedEvent: 'tokenCreatedEvent',
  TokenInfoEvent: 'TokenInfoEvent',
  FungibleTokenInfoEvent: 'FungibleTokenInfoEvent',
  NftMinted: 'NftMinted',
  PausedToken: 'PausedToken',
  UnpausedToken: 'UnpausedToken',
  CreatedToken: 'CreatedToken',
  TransferToken: 'TransferToken',
  MintedToken: 'MintedToken',
  CallResponseEvent: 'CallResponseEvent',
  GetTokenInfo: 'GetTokenInfo',
  MintedNft: 'MintedNft',
  GetFungibleTokenInfo: 'GetFungibleTokenInfo',
  GetNonFungibleTokenInfo: 'GetNonFungibleTokenInfo',
  TinyBars: 'TinyBars',
  TinyCents: 'TinyCents',
  PseudoRandomSeed: 'PseudoRandomSeed',
  CryptoAllowance: 'CryptoAllowance',
  IsAssociated: 'IsAssociated',
};

const Path = {
  BLOCK_INFO: 'contracts/solidity/block/BlockInfo.sol:BlockInfo',
  CRYPTO_MATH: 'contracts/solidity/cryptomath/CryptoMath.sol:CryptoMath',
  HIP583_ERC20Mock: 'contracts/mocks/ERC20Mock.sol:ERC20Mock',
  HIP583_ERC721Mock: 'contracts/hip-583/ERC721Mock.sol:ERC721Mock',
  HRC: 'contracts/hrc/HRC.sol:HRC',
  TYPE_OPS: 'contracts/solidity/typeops/TypeOps.sol:TypeOps',
  RECEIVER_PAYS:
    'contracts/solidity/signature-example/ReceiverPays.sol:ReceiverPays',
  RECEIVER: 'contracts/solidity/encoding/Receiver.sol:Receiver',
};

const Contract = {
  ERC20Mock: 'ERC20Mock',
  OZERC20Mock: 'OZERC20Mock',
  OZERC721Mock: 'OZERC721Mock',
  TokenCreateContract: 'TokenCreateContract',
  TokenCreateOpcodeLogger: 'TokenCreateOpcodeLogger',
  DiamondCutFacet: 'DiamondCutFacet',
  Diamond: 'Diamond',
  DiamondInit: 'DiamondInit',
  IDiamondCut: 'IDiamondCut',
  DiamondLoupeFacet: 'DiamondLoupeFacet',
  OwnershipFacet: 'OwnershipFacet',
  Test1Facet: 'Test1Facet',
  Test2Facet: 'Test2Facet',
  ERC1155Mock: 'ERC1155Mock',
  ContractTransferTx: 'ContractTransferTx',
  ERC721Contract: 'ERC721Mock',
  TokenCreateCustomContract: 'TokenCreateCustomContract',
  TokenManagementContract: 'TokenManagementContract',
  TokenQueryContract: 'TokenQueryContract',
  TokenTransferContract: 'TokenTransferContract',
  ERC20Contract: 'ERC20Contract',
  Exchange: 'Exchange',
  ExchangeV2: 'ExchangeV2',
  CounterV2: 'CounterV2',
  CounterV1: 'CounterV1',
  SafeOperations: 'SafeOperations',
  SafeViewOperations: 'SafeViewOperations',
  SafeHTS: 'SafeHTS',
  ERC20BurnableMock: 'ERC20BurnableMock',
  ERC20CappedMock: 'ERC20CappedMock',
  ERC20PausableMock: 'ERC20PausableMock',
  HRC719Contract: 'HRC719Contract',
  ExchangeRateMock: 'ExchangeRateMock',
  PrngSystemContract: 'PrngSystemContract',
  Concatenation: 'Concatenation',
  Transaction: 'Transaction',
  MessageFrameAddresses: 'MessageFrameAddresses',
  New: 'New',
  AssemblyAddress: 'AssemblyAddress',
  AddressContract: 'AddressContract',
  Recipient: 'Recipient',
  Inheritance: 'Inheritance',
  Functions: 'Functions',
  FunctionsChild: 'FunctionsChild',
  OpcodeLogger: 'OpcodeLogger',
  FunctionsParent: 'FunctionsParent',
  Scoping: 'Scoping',
  Arithmetic: 'Arithmetic',
  Defaults: 'Defaults',
  NonExisting: 'NonExisting',
  NonExtDup: 'NonExtDup',
  ControlStructures: 'ControlStructures',
  AssignmentReferenceTypes: 'AssignmentReferenceTypes',
  DestructuringReturns: 'DestructuringReturns',
  Panic: 'Panic',
  ReentrancyGuardTestSender: 'ReentrancyGuardTestSender',
  ReentrancyGuardTestReceiver: 'ReentrancyGuardTestReceiver',
  BlindAuction: 'BlindAuction',
  SimpleAuction: 'SimpleAuction',
  MyCustomTransparentUpgradeableProxy: 'MyCustomTransparentUpgradeableProxy',
  Box: 'Box',
  BoxV2: 'BoxV2',
  Encoding: 'Encoding',
  Sender: 'Sender',
  ErrorsExternal: 'ErrorsExternal',
  Errors: 'Errors',
  Main: 'Main',
  Base: 'Base',
  Modifiers: 'Modifiers',
  DerivedContract: 'DerivedContract',
  Token: 'Token',
  PaymentChannel: 'PaymentChannel',
  Precompiles: 'Precompiles',
  CryptoUnits: 'CryptoUnits',
  TimeUnits: 'TimeUnits',
  Ballot: 'Ballot',
  Bitwise: 'Bitwise',
  ContractCaller: 'ContractCaller',
  Target: 'Target',
  TargetContract: 'TargetContract',
  ContractCreator: 'ContractCreator',
  DataAllocation: 'DataAllocation',
  MathCoverage: 'MathCoverage',
  TransactionInfo: 'TransactionInfo',
  AccessControlContract: 'AccessControlContract',
  BeaconContract: 'MyBeacon',
  LogicContractV1: 'LogicContractV1',
  LogicContractV2: 'LogicContractV2',
  BeaconProxyContract: 'MyProxy',
  ContractCreatorOZCreate2: 'ContractCreatorOZCreate2',
  ERC20VotesTest: 'ERC20VotesTest',
  Test_ERC165: 'Test_ERC165',
  ClimberSelector: 'ClimberSelector',
  ERC1820Registry: 'ERC1820Registry',
  ERC777SenderHookImpl: 'ERC777SenderHookImpl',
  ERC777RecipientHookImpl: 'ERC777RecipientHookImpl',
  ERC777Token: 'ERC777Token',
  ERC777ContractAccount: 'ERC777ContractAccount',
  ERC1155Token: 'ERC1155Token',
  VoteV1: 'VoteV1',
  VoteV2: 'VoteV2',
  VoteProxy: 'VoteProxy',
  ERC2612Test: 'ERC2612Test',
  ERC2771ContextTest: 'ERC2771ContextTest',
  ERC2771ForwardTest: 'ERC2771ForwardTest',
  ERC2981Test: 'ERC2981Test',
  TokenVault: 'TokenVault',
  VestingWallet: 'VestingWallet',
  MulticallTest: 'MulticallTest',
  CrowdFund: 'CrowdFund',
  PausableTest: 'PausableTest',
  SafeCastTest: 'SafeCastTest',
  VaultV1: 'VaultV1',
  VaultV2: 'VaultV2',
  ShanghaiOpcodes: 'ShanghaiOpcodes',
  Counter: 'Counter',
  EcrecoverCaller: 'EcrecoverCaller',
  InvalidERC721Receiver: 'InvalidERC721Receiver',
  ValidERC721Receiver: 'ValidERC721Receiver',
  ExampleGovernor: 'ExampleGovernor',
  ExampleTokenVote: 'ExampleTokenVote',
  Purchase: 'Purchase',
  InternalCallee: 'InternalCallee',
  InternalCaller: 'InternalCaller',
  EthNativePrecompileCaller: 'EthNativePrecompileCaller',
  AtomicHTS: 'AtomicHTS',
  BLSTest: 'BLSTest',
  BlsBn254: 'BlsBn254',
  CryptoAllowance: 'CryptoAllowance',
  CryptoOwner: 'CryptoOwner',
  CancunOpcodes: 'CancunOpcodes',
  KZGPointEvaluation: 'KZGPointEvaluation',
  StateRegistry: 'StateRegistry',
  Airdrop: 'Airdrop',
  ClaimAirdrop: 'ClaimAirdrop',
  TokenReject: 'TokenReject',
  AliasAccountUtility: 'AliasAccountUtility',
  CancelAirdrop: 'CancelAirdrop',
};

const CALL_EXCEPTION = 'CALL_EXCEPTION';
const CONTRACT_REVERT_EXECUTED_CODE = 3;
const GAS_LIMIT_1_000_000 = { gasLimit: 1_000_000 };
const GAS_LIMIT_2_000_000 = { gasLimit: 2_000_000 };
const GAS_LIMIT_5_000_000 = { gasLimit: 5_000_000 };
const GAS_LIMIT_10_000_000 = { gasLimit: 10_000_000 };
const GAS_LIMIT_800000 = { gasLimit: 800000 };
const GAS_LIMIT_8000000 = { gasLimit: 8000000 };
const WEI = 1;
const ONE_HBAR = ethers.parseEther('1');
const TOKEN_NAME = 'tokenName';
const TOKEN_SYMBOL = 'tokenSymbol';
const TOKEN_URL = 'tokenUrl';
const TX_SUCCESS_CODE = 22;
const SECOND = 1;
const MINUTE = 60 * SECOND;
const HOUR = 60 * MINUTE;
const DAY = 24 * HOUR;
const WEEK = 7 * DAY;
const GWEI = 1e9;
const HTS_SYSTEM_CONTRACT_ID = '0.0.359';
const HAS_SYSTEM_CONTRACT_ID = '0.0.362';

module.exports = {
  Events,
  Path,
  Contract,
  CALL_EXCEPTION,
  CONTRACT_REVERT_EXECUTED_CODE,
  GAS_LIMIT_1_000_000,
  GAS_LIMIT_2_000_000,
  GAS_LIMIT_5_000_000,
  GAS_LIMIT_10_000_000,
  GAS_LIMIT_800000,
  GAS_LIMIT_8000000,
  ONE_HBAR,
  TOKEN_URL,
  TOKEN_NAME,
  TOKEN_SYMBOL,
  TX_SUCCESS_CODE,
  SECOND,
  MINUTE,
  HOUR,
  DAY,
  WEEK,
  WEI,
  GWEI,
  HTS_SYSTEM_CONTRACT_ID,
  HAS_SYSTEM_CONTRACT_ID,
};
