const hederaProto = require('@hashgraph/proto');
const fs = require('fs');
const shell = require('shelljs');

async function main() {
  let hederaResponseCodeContract =
      '// SPDX-License-Identifier: Apache-2.0\n' +
      'pragma solidity >=0.4.9 <0.9.0;\n' +
      '\n// this contract is auto-generated by a manual triggered script in utils/protobuf-parser.js' +
      '\n// documentation for each code can be found here https://github.com/hashgraph/hedera-services/blob/main/hapi/hedera-protobufs/services/response_code.proto\n\n' +
      'library HederaResponseCodes {\n';

  for (const [name, code] of Object.entries(hederaProto.proto.ResponseCodeEnum)) {
    hederaResponseCodeContract += `    int32 internal constant ${name} = ${code};\n`;
  }

  hederaResponseCodeContract += '}\n';

  fs.writeFileSync('./contracts/system-contracts/HederaResponseCodes.sol', hederaResponseCodeContract);
  shell.exec('npx hardhat compile');
}

main();
