name: ERC Registry Tool Test

on:
  pull_request:
    branches: [main, release/**]
  push:
    branches: [main, release/**]
    tags: [v*]

permissions:
  contents: read

jobs:
  run-test:
    name: ERC Registry Tool
    runs-on: smart-contracts-linux-large
    env:
      INDEXER_PATH: ./tools/erc-repository-indexer/erc-contract-indexer
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: recursive

      - name: Use Node.js [20]
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20

      - name: Create .env file
        run: cp ${{env.INDEXER_PATH}}/local.env ${{env.INDEXER_PATH}}/.env

      - name: Install Dependencies
        run: |
          npm ci
          cd ${{env.INDEXER_PATH}}
          npm install

      - name: Run Unit Tests
        run: |
          cd ${{env.INDEXER_PATH}}
          npm run test:unit

      - name: Start the local node
        run: npx hedera start -d --verbose=trace
        timeout-minutes: 5

      - name: Run Acceptance Tests
        run: |
          cd ${{env.INDEXER_PATH}}
          npm run test:acceptance

      - name: Stop the local node
        if: ${{ !cancelled() }}
        run: npx hedera stop
