name: ERC Registry Tool Test

on:
  pull_request:
    branches: [main, release/**]
  push:
    branches: [main, release/**]
    tags: [v*]

jobs:
  run-test:
    name: ERC Registry Tool
    runs-on: smart-contracts-linux-large
    env:
      INDEXER_PATH: ./tools/erc-repository-indexer/erc-contract-indexer
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive

      - name: Use Node.js [20]
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 20

      - name: Create .env file
        run: cp ${{env.INDEXER_PATH}}/local.env ${{env.INDEXER_PATH}}/.env

      - name: Install Dependencies
        run: |
          npm ci
          cd ${{env.INDEXER_PATH}}
          npm install

      - name: Run Unit Tests
        run: |
          cd ${{env.INDEXER_PATH}}
          npm run test:unit

      - name: Start the local node
        run: npx hedera start -d --verbose=trace
        timeout-minutes: 5

      - name: Run Acceptance Tests
        run: |
          cd ${{env.INDEXER_PATH}}
          npm run test:acceptance

      - name: Stop the local node
        if: ${{ !cancelled() }}
        run: npx hedera stop
