name: ERC Registry Tool Test

on:
  pull_request:
    branches: [main, release/**]
  push:
    branches: [main, release/**]
    tags: [v*]

permissions:
  contents: read

jobs:
  run-test:
    name: ERC Registry Tool
    runs-on: smart-contracts-linux-large
    env:
      INDEXER_PATH: ./tools/erc-repository-indexer/erc-contract-indexer
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: recursive

      - name: Use Node.js [20]
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20

      - name: Create .env file
        run: cp ${{env.INDEXER_PATH}}/local.env ${{env.INDEXER_PATH}}/.env

      - name: Install Dependencies
        run: |
          npm ci
          cd ${{env.INDEXER_PATH}}
          npm install

      - name: Run Unit Tests
        run: |
          cd ${{env.INDEXER_PATH}}
          npm run test:unit

      - name: Generate falcon-values config file
        run: |
          cat > .github/falcon.yml <<EOF
          network:
            --release-tag: "v0.72.0"
            --node-aliases: "node1"
          
          setup:
            --release-tag: "v0.72.0"
            --node-aliases: "node1"
          
          consensusNode:
            --node-aliases: "node1"
            --force-port-forward: true
          mirrorNode:
            --enable-ingress: true
            --pinger: true
            --mirror-node-version: "v0.151.0"
            --force-port-forward: true
          explorerNode:
            --enable-ingress: true
          relayNode:
            --node-aliases: "node1"
            --relay-release: "v0.75.0"
            --values-file: ".github/relay-values.yml"
          EOF

      - name: Setup Kind
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        with:
          install_only: true
          node_image: kindest/node:v1.32.5@sha256:e3b2327e3a5ab8c76f5ece68936e4cafaa82edf58486b769727ab0b3b97a5b0d
          version: v0.29.0
          kubectl_version: v1.32.5
          verbosity: 3
          wait: 120s

      - name: Start the solo node
        run: npx @hashgraph/solo@0.58.0 one-shot falcon deploy --values-file .github/falcon.yml --dev
        timeout-minutes: 15

      - name: Forward solo ports
        run: .github/scripts/forward-ports.sh

      - name: Run Acceptance Tests
        run: |
          cd ${{env.INDEXER_PATH}}
          npm run test:acceptance

      - name: Stop solo
        if: ${{ !cancelled() }}
        run: npx @hashgraph/solo@${{ inputs.soloVersion || '0.58.0' }} one-shot single destroy
