name: Migration Testing

on:
  workflow_dispatch:
    inputs:
      initialNetworkNodeTag:
        description: 'Specify initial Network Node image tag'
        required: true
        default: ''
      initialMirrorNodeTag:
        description: 'Specify initial Mirror-Node image tag'
        required: true
        default: ''
      initialRelayTag:
        description: 'Specify initial Hedera JSON-RPC Relay tag'
        required: true
        default: ''
      targetNetworkNodeTag:
        description: 'Specify target Network Node image tag'
        required: true
        default: ''
      targetMirrorNodeTag:
        description: 'Specify target Mirror-Node image tag'
        required: true
        default: ''
      targetRelayTag:
        description: 'Specify target Hedera JSON-RPC Relay tag'
        required: true
        default: ''
      preMigrationTestTags:
        description: 'Specify pre-migration test tags'
        required: false
        default: '@pre-migration'
      postMigrationTestTags:
        description: 'Specify post-migration test tags'
        required: false
        default: '@post-migration'
      soloVersion:
        description: 'Specify solo version'
        required: false
        type: string

jobs:
  check:
    name:
      Migration testing (${{ inputs.preMigrationTestTags }}/${{ inputs.postMigrationTestTags }}) with initial N:${{ inputs.initialNetworkNodeTag }}, M:${{ inputs.initialMirrorNodeTag }}, R:${{ inputs.initialRelayTag }} and
      target N:${{ inputs.targetNetworkNodeTag }}, M:${{ inputs.targetMirrorNodeTag }}, R:${{ inputs.targetRelayTag }}
    runs-on: smart-contracts-linux-large
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
        with:
          submodules: recursive

      - name: Use Node.js [20]
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20
          #cache: npm Disabling this because it causes the workflow to hang and eventually timeout

      - name: Create .env file
        run: cp local.env .env

      - name: Install dependencies
        run: npm install

      - name: Install Foundry
        uses: step-security/foundry-toolchain@ced99da5c56c695ce707ab2715ca678d6e8a7038 # v1.4.0
        with:
          version: stable

      - name: Generate falcon-values config file
        run: |
          cat > .github/initial.yml <<EOF
          network:
            --release-tag: "${{ inputs.initialNetworkNodeTag }}"
            --node-aliases: "node1"
          
          setup:
            --release-tag: "${{ inputs.initialNetworkNodeTag }}"
            --node-aliases: "node1"
          
          consensusNode:
            --node-aliases: "node1"
            --force-port-forward: true
          mirrorNode:
            --enable-ingress: true
            --pinger: true
            --mirror-node-version: "${{ inputs.initialMirrorNodeTag }}"
            --force-port-forward: true
          explorerNode:
            --enable-ingress: true
          relayNode:
            --node-aliases: "node1"
            --relay-release: "${{ inputs.initialRelayTag }}"
            --values-file: ".github/relay-values.yml"
          EOF
          cat > .github/target.yml <<EOF
          network:
            --release-tag: "${{ inputs.targetNetworkNodeTag }}"
            --node-aliases: "node1"
          
          setup:
            --release-tag: "${{ inputs.targetNetworkNodeTag }}"
            --node-aliases: "node1"
          
          consensusNode:
            --node-aliases: "node1"
            --force-port-forward: true
          mirrorNode:
            --enable-ingress: true
            --pinger: true
            --mirror-node-version: "${{ inputs.targetlMirrorNodeTag }}"
            --force-port-forward: true
          explorerNode:
            --enable-ingress: true
          relayNode:
            --node-aliases: "node1"
            --relay-release: "${{ inputs.targetRelayTag }}"
            --values-file: ".github/relay-values.yml"
          EOF

      - name: Setup Kind
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        with:
          install_only: true
          node_image: kindest/node:v1.32.5@sha256:e3b2327e3a5ab8c76f5ece68936e4cafaa82edf58486b769727ab0b3b97a5b0d
          version: v0.29.0
          kubectl_version: v1.32.5
          verbosity: 3
          wait: 120s

      - name: Start the solo node
        run: npx @hashgraph/solo@${{ inputs.soloVersion || '0.58.0' }} one-shot falcon deploy --values-file .github/initial.yml --dev
        timeout-minutes: 15

      - name: Forward solo ports
        run: .github/scripts/forward-ports.sh

      - name: Run pre-migration tests
        run: npx hardhat test --grep ${{ inputs.preMigrationTestTags }}
        timeout-minutes: 15

      - name: Freeze the network
        run: |
          npx hardhat run scripts/freeze-network-node.js
          sleep 30
        timeout-minutes: 5

      - name: Start the solo node with new network
        run: |
          npx @hashgraph/solo@${{ inputs.soloVersion || '0.58.0' }} one-shot single destroy
          npx @hashgraph/solo@${{ inputs.soloVersion || '0.58.0' }} one-shot falcon deploy --values-file .github/target.yml --dev
        timeout-minutes: 15

      - name: Run post-migration tests
        run: npx hardhat test --grep ${{ inputs.postMigrationTestTags }}
        timeout-minutes: 15
